version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: deathnote_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: bunta
      POSTGRES_DB: deathnote_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
    container_name: deathnote_backend
    depends_on:
      - postgres
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: bunta
      DB_NAME: deathnote_db
    ports:
      - "8080:8080"

  frontend:
    build:
      context: ./frontend
    container_name: deathnote_frontend
    depends_on:
      - backend
    environment:
      - VITE_API_URL=http://backend:8080
    ports:
      - "5173:5173"
    command: ["npm", "run", "dev", "--", "--host"]

volumes:
  postgres_data:
