version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://backend:8080
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - "8081:8080"  # ✅ Puerto externo 8081, interno sigue en 8080
    environment:
      - VITE_API_URL=http://backend:8080
      - DB_HOST=db
      - DB_USER=postgres
      - DB_PASSWORD=bunta
      - DB_NAME=deathnote_db
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=bunta
      - POSTGRES_DB=deathnote_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
